# Generated by Django 3.1.4 on 2020-12-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(max_length=300, upload_to='uploads/'),
        ),
    ]
