# Generated by Django 3.1.4 on 2020-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('institiute_name', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(null=True, related_name='student_proj', to='myapp.Project')),
            ],
        ),
    ]
